sudo: required
services:
    - docker

before_install:
    - docker build -t bhagath/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bhagath/react-test npm test -- --coverage

after_success:
    - docker build -t bhagathac/multi-client ./client
    - docker build -t bhagathac/multi-nginx ./nginx
    - docker build -t bhagathac/multi-server ./server
    - docker build -t bhagathac/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push bhagathac/multi-client
    - docker push bhagathac/multi-nginx
    - docker push bhagathac/multi-server
    - docker push bhagathac/multi-worker


