sudo: required
services:
    - docker

before_install:
    - docker build -t bhagath/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bhagath/react-test npm test -- --coverage

after_success:
    - docker build -t bhagathac/multi-client ./client
    - docker build -t bhagathac/multi-nginx ./nginx
    - docker build -t bhagathac/multi-server ./server
    - docker build -t bhagathac/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push bhagathac/multi-client
    - docker push bhagathac/multi-nginx
    - docker push bhagathac/multi-server
    - docker push bhagathac/multi-worker
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-167500560729"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY